"""added deleted_at for user

Revision ID: 3529f796ebba
Revises: bbe60daf8560
Create Date: 2026-07-22 14:56:00.149285

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3529f796ebba"
down_revision: str | Sequence[str] | None = "bbe60daf8560"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("refresh_token_user_id_fkey"), "refresh_token", type_="foreignkey")
    op.create_foreign_key(None, "refresh_token", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=320), nullable=True)
    op.drop_constraint(op.f("user_social_account_user_id_fkey"), "user_social_account", type_="foreignkey")
    op.create_foreign_key(None, "user_social_account", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_social_account", type_="foreignkey")
    op.create_foreign_key(op.f("user_social_account_user_id_fkey"), "user_social_account", "user", ["user_id"], ["id"])
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=320), nullable=False)
    op.drop_column("user", "deleted_at")
    op.drop_constraint(None, "refresh_token", type_="foreignkey")
    op.create_foreign_key(op.f("refresh_token_user_id_fkey"), "refresh_token", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
